# Morley's trisector theorem, proved here by literal equality of exact numbers.

using AlgebraicNumbers
include("exact_geometry.jl")
using .ExactGeometry

# A deliberately non-symmetric triangle: A = π/7, B = 2π/7, C = 4π/7.
# Its trisectors live in the degree-12 real subfield generated by 21st roots.
A, B, C = 1//7, 2//7, 4//7
@assert A + B + C == 1

pA = AlgebraicNumber[0, 0]
pB = AlgebraicNumber[1, 0]
pC = ExactGeometry.intersect(line_from_angle(pA, A), line_from_angle(pB, 1 - B))

# Each point is the intersection of the two trisectors adjacent to one side.
mAB = ExactGeometry.intersect(line_from_angle(pA, A / 3), line_from_angle(pB, 1 - B / 3))
mBC = ExactGeometry.intersect(line_from_angle(pB, 1 - 2B / 3), line_from_angle(pC, 2 - B - C / 3))
mCA = ExactGeometry.intersect(line_from_angle(pC, 1 + A + C / 3), line_from_angle(pA, A - A / 3))

side12_squared = squared_distance(mAB, mBC)
side23_squared = squared_distance(mBC, mCA)
side31_squared = squared_distance(mCA, mAB)
d12 = sqrt(side12_squared)
d23 = sqrt(side23_squared)
d31 = sqrt(side31_squared)

@assert d12^2 == d23^2 == d31^2
println("Morley triangle squared side length: $side12_squared")
println("Exact check: d12^2 == d23^2 == d31^2")
